name: Pull Request Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - uses: actions/cache@v4
        with:
          path: .turbo
          key: turbo-cache-${{ github.ref_name }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            turbo-cache-${{ github.ref_name }}-

      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: lts/*
          registry-url: https://npm.pkg.github.com

      - run: pnpm install --frozen-lockfile
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}

      - run: pnpm build
        shell: bash
